main/urls.py
from django.urls import path
from .views import *

# urlpatterns = [
#     path('', HomeView.as_view(), name='home'),
#     path('about/', AboutView.as_view(), name='about')
# ]

posts/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', home, name="home"),
    path("create/", create, name="posts_create"),
    path("delete/<int:id>", delete, name= "posts_delete"),
    path("update/<int:id>", update, name= "posts_update"),
    path('about', AboutView.as_view(), name="about"),
]

world/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class CategoryModel(models.Model):
    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name



    class Meta:
        verbose_name = "category"
        verbose_name_plural = "Categories"

class PostModel(models.Model):
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.TextField(max_length=100)
    image = models.ImageField(upload_to = 'images/', null = True)
    create_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    update_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

#
# def home(request):
#     return render(request, 'home.html')

#
# class HomeView(TemplateView):
#     template_name = 'home.html'
#
#
#
# class AboutView(TemplateView):
#     template_name = 'about.html'

posts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from .models import *
from django.shortcuts import *


# class HomeView(ListView):
#     model = Post
#     template_name = "home.html"


class AboutView(TemplateView):
    template_name = 'about.html'



def home(request):
    context = {
        'posts': PostModel.objects.all(),
        'category': CategoryModel.objects.all()
    }
    return render(request, "home.html", context)




def create(request):
    if request.method == "POST":
        p= PostModel(title=request.POST['title'], text=request.POST['text'])
        p.save()
        return redirect("home")

    return render(request, "create.html")


def update(request, id):
    try:
        p = PostModel.objects.get(id=id)
    except PostModel.DoesNotExist:
        return redirect("home")

    if request.method == "POST":
        p.title =request.POST['title']
        p.text = request.POST['text']
        p.save()

        return redirect("home")

    return render(request, "create.html", {
        "p": p
    })


def delete(request, id):
    PostModel.objects.filter(id=id).delete()
    return redirect("home")

main/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h3>1234</h3>
{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="{% static " vender/bootstrap/css/bootstrap.css " %}">
    <link rel="stylesheet" href="{% static " vender/bootstrap-icons/bootstrap-icons.css " %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>


<header class="container">


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">World</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>

                </ul>

            </div>
        </div>
    </nav>
</header>
<div class="container" py-4>
    {% block content %}
    {% endblock content %}
</div>
<footer class="bg-dark text-white py-5 w-100">
    <div class="container">
        <div class="row">
            <div class="col-4 offset-4 d-flex justify-content-around ">
                <i class="bi bi-instagram" style="font-size: 30px"></i>
                <i class="bi bi-facebook" style="font-size: 30px"></i>
                <i class="bi bi-telegram" style="font-size: 30px"></i>
                <i class="bi bi-github" style="font-size: 30px"></i>
            </div>
        </div>
    </div>
</footer>


<script src="{% static " vender
/jquery-3.6.0.min.js" %}"></script>
<script src="{% static " vender
/bootstrap/js/bootstrap.bundle.js" %}"></script><!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>
</html>

main/templates/create.html
{% extends "base.html" %}

{% block content %}

    <div class="cotainer">
        <form action="{% if p %}{% url "posts_update" p.id %}{% else %}{% url "posts_create" %}{% endif %}" method = "post" >
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title"> Davlat nomi:</label>
                <input id="id_title" type="text" name="title" value="{{ p.title }}" class="form-control" placeholder="Davlatning nomini kiriting...">
            </div>
            <div class="form-group">
                <label for="id_text">Markazi:</label>
                <input type="text" name="text" id="id_text" value="{{ p.text }}" class="form-control" placeholder="Sharnomini kiriting...">
            </div>
            <button type="submit" class="btn btn-success">Saqlash</button>
        </form>
    </div>

{% endblock content %}

main/templates/home.html
{% extends "base.html" %}

{% block content %}
        <div class="row mb-3">
            <div class="col text-right py-4">
               <a href="{% url "posts_create" %}" class="btn btn-info"> Qo'shish </a>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                <div class="py-3 sticky-top">
                    <div class="list-group">
                        {% for c in category %}
                        <a href="#" class="list-group-item list-group-item-action " aria-current="true">
                            {{ c.name }}
                        </a>

                        {% endfor %}
                    </div>
                </div>

            </div>
            <div class="col-9">
                <div class="row">
                   {% for post in posts %}
                            <div class="col-4">
                                <div class="card" >
                                    <img src="{{ post.image.url}}" class="card-img-top" style = "width: 100%; height:250" >
                                    <div class="card-body">
                                        <h4>{{post.title}}</h4>
                                        <p class="card-text">{{post.text}}.</p>
                                        <div class= "py-2 mt-3 d-flex justify-content-between">
                                            <a href="{% url "posts_update" post.id %}" class="btn btn-warning px-4 py-2">
                                                <i class="bi bi-pencil"></i>
                                            </a>
                                            <a href="{% url "posts_delete" post.id %}" class="btn btn-primary px-4 py-2">
                                                <i class="bi bi-trash"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>


                   {% empty %}


                        <div class="container text-center">
                            <h4>Davlatlar mavjud emas !!!</h4>
                        </div>
                   {% endfor %}
                </div>
            </div>

        </div>


{% endblock %}